[package]
name = "rocket-webapi"
version = "0.1.0"

[dependencies]
rocket = "0.4"
rocket_contrib = { version = "0.4", features = ["json"] }
serde = "1.0.0"
serde_json = "1.0.0"
serde_derive = "1.0.0"
chrono = "0.4.3"
